### ISSUE TITLE
Issue with Server Side

### ISSUE THREAD

**Issue by SharkieTV** [CrimsonDawn45/Basic-Shields-Fabric-#6]
So im trying to add your mod to the Better Minecraft FABRIC version. 
When testing server side it constantly spams menu.preparingSpawn instead of the % of world generation.
Can you fix this?

Log: https://pastebin.com/Bem8EUhV

**Comment by CrimsonDawn45** [comment]
Yeah, it's because if you rename a vanilla item it screws up a bunch of language stuff. I'm gonna have to see if there is some way to fix that while still allowing me to rename the vanilla shield to Iron Shield.
